name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        name: Setup npm package
        command: npm init -y && npm install
      - name: Chrome
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          command: npm test
          browser: chrome