name: main
on: [push]

jobs:
  # TODO: add some test jobs

  release:
    runs-on: ubuntu-20.04
    name: release
    # only release from the master branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3