name: Sauce demo
on:
  schedule:    
    - cron: '0 7 * * *'
jobs:
    cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup npm package
        run: npm init -y && npm install
      - name: Regression test
        uses: cypress-io/github-action@v5.0.2
        with:                          #          
          command: npm run test    