name: main
on: [push]

jobs:
  cross-browser:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Chrome run
        uses: cypress-io/github-action@v4.2.0 
        with:
          command: npm run chrome
      - name: Edge run
        uses: cypress-io/github-action@v4.2.0 
        with:
          command: npm run edge