name: Ubuntu
on: [push]
jobs:
  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      # print Ubuntu version
      - run: cat /etc/lsb-release
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5